### ISSUE TITLE
Error: Pull Request is not mergable

### ISSUE THREAD

**Issue by jcquiles** [juliangruber/merge-pull-request-action#17]
Hey @juliangruber im attempting to create a PR to merge a dev branch into a qa branch. However, seeing an error message when this runs on the merge PR job of the workflow. The error appears with the message **Error: Pull Request is not mergable.** I hoping you had some recent incite on this error? It seems there are a few checks missing, if the number: 1 shouldn't be there, how can I correct that? Thanks! 

```
Run juliangruber/merge-pull-request-action@v1
  with:
    github-token: ***
    number: 1
    method: merge
Error: Pull Request is not mergeable
```

**Comment by juliangruber** [comment]
Hey @jcquiles, `number` should be the specific number of your pull request, can you please verify you're passing it correctly?

**Comment by jcquiles** [comment]
@juliangruber thanks for getting back! how can I verify am I passing the correct commit? which part in my yaml script would actually control that number 1?

**Comment by juliangruber** [comment]
You're not passing commits there. If you wanted to merge this PR for example https://github.com/juliangruber/merge-pull-request-action/pull/2, then you'd pass number 2, because the PR has the number 2. You need to either know or read the number of the PR from environment variables, see https://github.com/actions/checkout/issues/58 for inspiration

**Comment by jcquiles** [comment]
I see, so in the yaml file, the **specific PR** would need to be specified by env variable such as **$GITHUB_EVENT_PATH** correct?

- here is what im looking at currently

```
      - name: create deploy-qa branch from react-dev
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "deploy-qa"

      - name: create PR to deploy to QA
        uses: peter-evans/create-pull-request@v3
        with:
          branch: deploy-qa
          base: react-qa
          title: QA Deploy (${{ github.actor }})
          commit-message: create PR to deploy react-dev to react-qa
          body: Auto-generated PR (via Github Actions manual workflow) to deploy react-dev to react-qa. Intiated by ${{ github.actor }}.
          delete-branch: true
```
