### ISSUE TITLE
Invalid value for parameter 'pull_number': "" is NaN

### ISSUE THREAD

**Issue by nvtanhh** [juliangruber/merge-pull-request-action#24]
I can't merge the PR because of this error.

My workflows:
    
   ```
    - name: Raise PR
       id: raise_pr
       uses: peter-evans/create-pull-request@v4.2.1
       with:
           token: ${{ secrets.GITHUB_TOKEN }}
           commit-message: "[no ci] Build staging"
           delete-branch: true
           title: "Build Staging version ${{ steps.version.outputs.new-version }}"
           body: ${{github.event.head_commit.message}}
           add-paths: pubspec.yaml
           branch: "staging-version"
           base: "staging"
           labels: "automerge"
     - name: Merge PR
        uses: juliangruber/merge-pull-request-action@v1.1.0
        env:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          number: ${{ steps.raise_pr.outputs.pull-request-number }}
          method: squash
```
