### ISSUE TITLE
merged to master branch won't trigger GH action pipeline

### ISSUE THREAD

**Issue by krtschmr** [juliangruber/merge-pull-request-action#26]
- create PR via GH action (triggers pipeline)
- merge PR via GH action 

outcome: 
PR is merged, no action ran, thus no deployment. 

```
name: "[Schedule] Merge daily release PR"
on:
  workflow_dispatch:
  schedule:
    - cron: 15 8 * * 1-5 # At 08:15 (UTC) on every day-of-week from Monday through Friday

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: branch name
        id: branch
        run: echo "name=release-$(date +%y)-$(date +%j)" >> $GITHUB_OUTPUT

      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{steps.branch.outputs.name}}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
          method: merge

```

PR was created with

```

      - uses: repo-sync/pull-request@v2
        name: pull-request
        with:
          source_branch: ${{ steps.branch.outputs.name }}
          destination_branch: "master"
          pr_title: "🚢 ${{ steps.branch.outputs.name }} - SHIP IT :shipit:"
          pr_body: |
            ${{ steps.vars.outputs.pr_body }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

```

anybody ever had that?
