### ISSUE TITLE
Pull Request is not mergeable

### ISSUE THREAD

**Issue by Ryukote** [juliangruber/merge-pull-request-action#4]
Hi,

this is my workflow:

```
name: Test Pipeline

on: [pull_request]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build ./ConsoleApp1/ConsoleApp1.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./ConsoleApp1/ConsoleApp1.sln
      
  pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: "${{ secrets.TOKEN }}"
        number: 1

```

For some reason on 'pull-request' it breaks with message "##[error]Pull Request is not mergeable".
I have 1 active pull request which I can manually merge inside Github (there are no merge conflicts).

Do you maybe have a vision what am I doing wrong here?

Thank you
